global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'pielarmonia'
      scheme: http
      metrics_path: '/api.php'
      params:
          resource: ['metrics']
      static_configs:
          - targets: ['host.docker.internal:8080'] # Targets the host machine's PHP server
